### ISSUE TITLE
Mixed-prefix unification

### ISSUE THREAD

**Issue by jamescheney** [jstolarek/inferno#17]
Consider the following examples:
```
(* mixed_prefix_1 *)
  let (x : ∀ a.((∀ b.  a → a) → int)) = λ(y:∀ b.  a → a). 42 in
  let (z : ∀ b.  b → b) =  λw. w in
  x (~z)
(* mixed_prefix_2 *)
  let (x : (∀ a.((∀ b.  b → a) → int)) = λ(y:∀ b.  b → a). 42 in
  let (z : ∀ b.  b → Int) =  λw. 42 in
  x (~z)
```

The first one is designed to force the unifier to solve the problem `exists X. forall a. a -> a == forall a. X -> X` which should fail because unifying `X` with `a` should not be allowed if `a` was not in scope when `X` was introduced.  

The second one is designed to force the unifier to solve a problem `exists X. forall a. a -> Int == forall a. a -> X` which should succeed with `X == Int`.

Currently (4e19f88) both fail with implementation bugs.  The failures seem related to the lack of handling quantified variables of type ascriptions on lambda-bound variables (example `poly_binding_2` in #16 ).

**Comment by jstolarek** [comment]
After fixing #16 `mixed_prefix_2` works as expected.

**Comment by jstolarek** [comment]
`mixed_prefix_1` doesn't work as expected. Here's what happens. We have:
```
let (x : ∀ a.(∀ b. a → a) → Int) = λ(y:∀ b. a → a). 1 in
let (z : ∀ b. b → b) = λw. w in
x (~z)
```
We should reject `x (~z)` application. We freeze `z` - its type is `∀ c. c → c`, where `c` is a skolem. We then unify it with `∀ b. a → a` and unification succeeds since there's no reason at this point why it should fail. One potential solution to test would be to skolemize all free type variables. It would work in this case but I'm not sure whether this is a universal solution.

I'm also concerned about System F term produced for this example:
```
Pretty-printing the System F term...
  Λ30. let x = Λ31. λ(y : ∀ [31]. 31 → 31). 1 in
  let z = Λ10. λ(w : 10). w in
  x [30] z
```
This doesn't look correct. Concretely, the quantifier in the signature on `y` should be fresh and not `31`.

**Comment by jamescheney** [comment]
`mixed_prefix_1` should fail since there is no type we can instantiate `a` with that will result in a type unifying with `forall c. c -> c` - by capture avoidance whatever type we substitute for `a` in `forall b. a -> a` will not be able to mention `b` (if `b` occurs in the substituted type then the quantifier has to be renamed).

So, the behavior of the System F term is irrelevant since we shouldn't be producing it in the first place.

In the paper this is handled by renaming the quantified names when we unify two polymorphic types to common names.  (In the paper we do this one at a time but we can also easily do this for all pairs of names simultaneously.)  I think/hope that some mechanism analogous to ranks could be used to detect when an existential variable is unified with a universal variable that was not in scope when the existential was introduced, but I suspect the details to be tricky.

**Comment by jstolarek** [comment]
> So, the behavior of the System F term is irrelevant since we shouldn't be producing it in the first place.

Yes, exactly.

> In the paper this is handled by renaming the quantified names when we unify two polymorphic types to common names.

Names (`id`s) don't play a role during unification in inferno, i.e. we don't unify by name.

**Comment by jstolarek** [comment]
Here's a very good example that @jamescheney came up with:

```
(λx. let y : ∀ a. a → a = λz.x in y) 1 true
```

This is now in the testsuite as `mixed_prefix_3`.

**Comment by jstolarek** [comment]
@jamescheney, I implemented the solution mentioned in our yesterday call and it works. The idea is to prevent unification of skolems and existential variables (the latter are easily identified by having rank > 0). `mixed_prefix_2` does not currently work but for a different reason, unrelated to mixed-prefix unification (although mixed-prefix unification exposes the problem). I'm closing this ticket and will open another one for the problem triggered by `mixed_prefix_2`.
